import { isAutoGeneratedUsername } from './username.js';

function parseProfile(data) {
  const grudgeId = data.grudgeId || data.grudge_id || data.user?.grudgeId || data.user?.grudge_id;
  if (!grudgeId) return null;

  const username = data.username || data.displayName || data.user?.username || 'Player';

  return {
    grudgeId,
    username,
    displayName: data.displayName || username,
    userId: data.userId || data.user?.id || data.id || null,
    email: data.email || data.user?.email || null,
    needsProfile: Boolean(data.needsProfile),
    isAutoUsername: isAutoGeneratedUsername(username),
  };
}

export async function fetchGrudgeProfile(token, authUrl, cookie = null) {
  const headers = {};
  if (token) headers.Authorization = `Bearer ${token}`;
  if (cookie) headers.Cookie = cookie;

  const response = await fetch(`${authUrl}/api/auth/me`, { headers });
  if (!response.ok) return null;

  const data = await response.json();
  return parseProfile(data);
}

export async function fetchGrudgeProfileFromRequest(req, authUrl) {
  const token = (req.headers.authorization || '').startsWith('Bearer ')
    ? req.headers.authorization.slice(7).trim()
    : null;
  const cookie = req.headers.cookie || null;
  if (!token && !cookie) return null;
  return fetchGrudgeProfile(token, authUrl, cookie);
}

export async function completeGrudgeProfile(token, authUrl, { username, email }, cookie = null) {
  const body = {};
  if (username) body.username = username;
  if (email) body.email = email;

  const headers = { 'Content-Type': 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;
  if (cookie) headers.Cookie = cookie;

  const response = await fetch(`${authUrl}/api/auth/complete-profile`, {
    method: 'POST',
    headers,
    body: JSON.stringify(body),
  });

  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = data.error || data.message || 'Could not update Grudge username';
    const error = new Error(message);
    error.status = response.status;
    throw error;
  }

  return {
    grudgeId: data.grudgeId || data.grudge_id,
    username: data.username || data.displayName || username,
    displayName: data.displayName || data.username || username,
    needsProfile: Boolean(data.needsProfile),
  };
}

export function needsUsernameSetup(_profile, playerRecord) {
  return !playerRecord?.usernameSetupComplete;
}