const USERNAME_RE = /^[a-zA-Z0-9_-]{3,30}$/;
const WOW_LOGIN_RE = /^[a-zA-Z0-9]{1,16}$/;

export function isValidGrudgeUsername(value) {
  return typeof value === 'string' && USERNAME_RE.test(value.trim());
}

export function isAutoGeneratedUsername(username) {
  if (!username || typeof username !== 'string') return true;
  const name = username.trim();
  return (
    name.startsWith('puter:') ||
    name.startsWith('Puter_') ||
    name.startsWith('guest_') ||
    name.startsWith('Guest_') ||
    name.startsWith('discord:') ||
    name.startsWith('wallet:') ||
    name.startsWith('phone:') ||
    /^puter_[a-f0-9]+$/i.test(name) ||
    name === 'Player' ||
    name === 'User'
  );
}

export function sanitizeWowLogin(username, grudgeId) {
  const base = (username || 'player')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .slice(0, 12) || 'player';

  const suffix = (grudgeId || '')
    .replace(/[^a-z0-9]/gi, '')
    .slice(0, 4)
    .toLowerCase();

  let login = `${base}${suffix}`.slice(0, 16);
  if (!WOW_LOGIN_RE.test(login)) {
    login = `g${suffix || 'wow'}`.slice(0, 16);
  }
  return login;
}

export function generateWowPassword(grudgeId) {
  const seed = (grudgeId || 'wow').replace(/[^a-zA-Z0-9]/g, '');
  const tail = Buffer.from(seed).toString('base64url').replace(/[^a-zA-Z0-9]/g, '');
  return `Gw${tail.slice(0, 10)}!`;
}